export const actions = {
    SET_POKEMONS: "SET_POKEMONS",
    SET_FILTERED_POKEMONS: "SET_FILTERED_POKEMONS",
    SELECT_POKEMON: "SELECT_POKEMON",
    SHOW_POKEMON_FORM: "SHOW_POKEMON_FORM",
    HIDE_POKEMON_FORM: "HIDE_POKEMON_FORM"
}